package com.semeia_nordeste.backend.model;

public enum StatusEntrega {
    PEDIDO_RECEBIDO,
    PREPARANDO,
    AGUARDANDO_ENTREGADOR,
    ENTREGADOR_ACEITOU,
    PEDIDO_EM_COLETA,
    SAIU_PARA_ENTREGA,
    ENTREGUE,
    RETIRADA_DISPONIVEL,
    AGUARDANDO_RETIRADA,
    CANCELADO
}